# Generated by Django 5.1.6 on 2025-02-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("desciption", models.CharField(max_length=20)),
                ("picture", models.CharField(max_length=70)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
