# Generated by Django 5.1.6 on 2025-02-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="desciption",
            new_name="description",
        ),
    ]
