# Generated by Django 5.1.6 on 2025-02-14 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_desciption_listing_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 14, 15, 14, 22, 310289)
            ),
        ),
    ]
