# Generated by Django 5.1.6 on 2025-02-14 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listing_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 14, 15, 20, 43, 409052)
            ),
        ),
    ]
