# Generated by Django 5.1.6 on 2025-02-14 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_rename_name_listing_title_alter_listing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 14, 15, 21, 29, 991804)
            ),
        ),
    ]
