# Generated by Django 5.1.6 on 2025-02-14 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_listing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 14, 15, 53, 26, 864689)
            ),
        ),
    ]
