# Generated by Django 5.1.6 on 2025-02-14 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_listing_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="picture",
        ),
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(default="test", upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 14, 17, 12, 23, 783439)
            ),
        ),
    ]
