# Generated by Django 5.1.6 on 2025-02-14 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_remove_listing_picture_listing_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 14, 17, 40, 31, 645780)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(default="test", upload_to="static/uploads/"),
        ),
    ]
