# Generated by Django 5.1.6 on 2025-02-14 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_listing_date_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 14, 17, 46, 19, 804774)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(default="test", upload_to="uploads/"),
        ),
    ]
