# Generated by Django 5.1.6 on 2025-02-14 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_alter_listing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 14, 18, 3, 0, 250)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(default="test", upload_to="media/uploads/"),
        ),
    ]
