# Generated by Django 5.1.6 on 2025-02-14 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_listing_watchlist_alter_listing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 14, 23, 23, 6, 607864)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(),
        ),
    ]
