# Generated by Django 5.1.6 on 2025-02-14 23:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_alter_listing_date_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="listingTitle",
        ),
        migrations.AddField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.listing",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 14, 23, 38, 33, 491716)
            ),
        ),
    ]
