# Generated by Django 5.1.6 on 2025-02-15 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0021_rename_comment_comment_text_comment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="categoryName",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 15, 20, 38, 45, 769485)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 15, 20, 38, 45, 768711)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=60),
        ),
    ]
