# Generated by Django 5.1.6 on 2025-02-15 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0022_alter_category_categoryname_alter_comment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 15, 20, 39, 25, 590999)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 15, 20, 39, 25, 590220)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(max_length=300),
        ),
    ]
