# Generated by Django 5.1.6 on 2025-02-17 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_comment_date_alter_listing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 14, 55, 43, 848740)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 14, 55, 43, 847830)),
        ),
    ]
