# Generated by Django 5.1.6 on 2025-02-17 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_comment_date_alter_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 15, 8, 19, 145502)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 15, 8, 19, 144618)),
        ),
    ]
